export {
  register,
  login,
  refresh,
  logout,
  logoutAll,
  me,
  setRecoveryEmail,
  verifyRecoveryEmail,
  removeRecoveryEmail,
  setPassword,
  changePassword,
  initiateRecovery,
  completeRecovery,
} from '../modules/identity/interface/http/authController.js';
