export {
  search,
  getProviders,
  searchProvider,
  getInfo,
  getEpisodeSources,
  getEpisodeServers,
  getChapterPages,
  getAllTrending,
  getTrendingMovies,
  getTrendingTV,
  getTrendingAnime,
  getPopularAnime,
  getPopularManga,
  getTrendingGames,
  getPopularGames,
} from '../modules/catalog/interface/http/mediaSearchController.js';
